Authentication
mundaro/brandweerportaal-backend pull request #1
Opened 2021-10-18 18:53 UTC by SimonRijn

Swagger API documentatie te vinden op 'localhost:4000/swagger' 

Alleen beschikbaar tijdens het draaien van de development API

Graag alles benoemen wat beter kan of als dingen niet werken

2021-10-18 19:17 UTC, SimonRijn commented
Zitten nog een paar bugs in merk ik nu. Met name het de rollen gebaseerde acties. Fix komt er aan in de Users branch :-)

2021-10-19 07:50 UTC, ThijmenMaus requested changes
Paar kleine dingen aanpassen, voor de rest prachtig

2021-10-19 07:50 UTC, ThijmenMaus commented on src/auth/passport/jwt.strategy.ts
> +  public async validate(payload: any, req: any, done: Function) {
in deze functie grag wat spacing hier en daar

2021-10-19 07:50 UTC, ThijmenMaus commented on src/common/dto/response.dto.ts
> +    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
graag geen eslint disables

2021-10-19 07:50 UTC, ThijmenMaus commented on src/common/dto/response.dto.ts
> +    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
eslint idem

2021-10-19 09:07 UTC, merged